# Resolve the CELEX identifier of: 'COMMITTEE OF THE REGIONS DECISION No 18/2020'
# The Committee of the Regions uses a different register, meaning the number of the decision is not present in the CELEX id and URL

PREFIX cdm:<http://publications.europa.eu/ontology/cdm#>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX lang:<http://publications.europa.eu/resource/authority/language/>
        
SELECT DISTINCT 
    ?workId as ?id
    ?title
WHERE {  

    ?exp cdm:expression_belongs_to_work ?s .
    ?exp cdm:expression_title ?title .

    ?exp cdm:expression_uses_language ?lang .
    filter(?lang=lang:ENG) .  
     
    ?s cdm:work_created_by_agent <http://publications.europa.eu/resource/authority/corporate-body/COR> . 
    ?s cdm:work_id_document ?workId. 
    FILTER ((
        STRSTARTS( ?workId, "celex:32020") AND 
        REGEX( ?title, "[   ]18/2020")
    ))
}